language: php

php:
  - 8.0
  - 8.1

before_script:
  - travis_retry composer install --prefer-dist --no-interaction

cache:
  directories:
    - vendor

script:
  - vendor/bin/phpunit  --testdox --verbose